export const routes = {
  home: "/",
  produtos: "/produtos",
  categoria: (slug: string) => `/categoria/${slug}`,
  produto: (slug: string) => `/produtos/${slug}`,
  busca: (q?: string) => (q ? `/busca?q=${encodeURIComponent(q)}` : "/busca"),
  carrinho: "/carrinho",
  checkout: "/checkout",
  pagamento: (orderId: string) => `/pagamento/${orderId}`,
  pedidoConfirmado: (orderId: string) => `/pedido-confirmado/${orderId}`,
  acompanharPedido: "/acompanhar-pedido",

  admin: {
    login: "/admin/login",
    dashboard: "/admin/dashboard",
    pedidos: "/admin/pedidos",
    pedido: (id: string) => `/admin/pedidos/${id}`,
    produtos: "/admin/produtos",
    novoProduto: "/admin/produtos/novo",
    editarProduto: (id: string) => `/admin/produtos/${id}/editar`,
    categorias: "/admin/categorias",
    cupons: "/admin/cupons",
    clientes: "/admin/clientes",
    cliente: (id: string) => `/admin/clientes/${id}`,
    relatorios: "/admin/relatorios",
    configuracoes: "/admin/configuracoes",
    banners: "/admin/banners",
    anuncios: "/admin/anuncios",
    feedbacks: "/admin/feedbacks",
    previewMobile: "/admin/preview-mobile",
  },
} as const;
